Finalize the khr-3hv environment.
aidudezzz/deepworlds pull request #49
Opened 2021-08-20 09:46 UTC by NickKok

Finalize the khr-3hv environment for the GSoC 2021.

- Create the environment that works with Ray and Stable-Baseline PPO.
- Logging on Wandb website.
- Step-by-step documentation.

2021-08-30 14:30 UTC, KelvinYang0320 commented
Hello, @NickKok. I am reviewing the khr-3hv part of your work.
Did you get _AttributeError: module 'aioredis' has no attribute 'create_redis_pool'_  when `USE_Ray = True`?
Check out [this link](https://githubmemory.com/repo/aio-libs/aioredis/issues/1082).
I downgraded aioredis to v1.3.1  to run and keep reviewing  your work for now.

2021-08-31 02:43 UTC, KelvinYang0320 requested changes
Thank you for this khr-3hv example and the nice tutorial you provided!
I think users will enjoy this example.
I've left a few comments for khr-3hv.

2021-08-31 02:43 UTC, KelvinYang0320 commented on examples/khr-3hv/full project/controllers/supervisorsManager/PPORun.py
> +from scipy.ndimage.interpolation import shift
I think we can remove this unused `shift`.

2021-08-31 02:43 UTC, KelvinYang0320 commented on examples/khr-3hv/full project/controllers/supervisorsManager/PPORun.py
> +from ray.tune import grid_search
I think we can remove this unused import.

2021-08-31 02:43 UTC, KelvinYang0320 commented on examples/khr-3hv/full project/controllers/supervisorsManager/PPORun.py
> +from ray.tune.integration.wandb import wandb_mixin
I think we can remove this unused import.

2021-08-31 02:43 UTC, KelvinYang0320 commented on examples/khr-3hv/full project/controllers/supervisorsManager/PPORun.py
> +from ray.tune.logger import DEFAULT_LOGGERS
I think we can remove this unused  `DEFAULT_LOGGERS`.

2021-08-31 02:43 UTC, KelvinYang0320 commented on examples/khr-3hv/full project/worlds/khr-3hv.wbt
> +}
```suggestion
Viewpoint {
  fieldOfView 0.660595
  position 0.05 1.4 9
}
```
The viewpoint is a little bit too inclined.
Please update the gif in the readme file as well, thanks!

2021-08-31 02:43 UTC, KelvinYang0320 commented on examples/khr-3hv/README.md
> +![Solved cartpole demonstration](images/khr-3hv.gif)
The viewpoint is a little bit too inclined.
See the suggestion in khr-3hv.wbt.
Also, typo: `![Solved khr-3hv demonstration](images/khr-3hv.gif)`.
I think it would be better to put a reward plot from images folder next to this gif.

2021-08-31 02:43 UTC, KelvinYang0320 commented on examples/khr-3hv/full project/controllers/supervisorsManager/khr3hvEnv.py
> +        maxAct = 2.356 * np.ones(6)
These two lines cause user warning.
_UserWarning: We recommend you to use a symmetric and normalized Box action space (range=[-1, 1])_
See [this link](https://stable-baselines.readthedocs.io/en/master/_modules/stable_baselines/common/env_checker.html).
```suggestion
        lowAct = -1 * np.ones(6)
        maxAct = 1 * np.ones(6)
```
Also, we may need to modify the related code in other sections to keep this action space, i.e., `apply_action`

2021-08-31 02:43 UTC, KelvinYang0320 commented on examples/khr-3hv/full project/controllers/supervisorsManager/khr3hvEnv.py
> +            self.motorList[i].setPosition(ac)
```suggestion
        for i, ac in enumerate(motorIndexes, action):
            self.motorPositionArr[i] += ac*2.356
            self.motorList[i].setVelocity(self.motor_velocity)
            self.motorList[i].setPosition(ac)
```
`enumerate` allows us to loop over something and have an automatic counter.
`ac*2.356` is from the suggestion on _UserWarning: We recommend you to use a symmetric and normalized Box action space (range=[-1, 1])_

2021-08-31 02:43 UTC, KelvinYang0320 commented on examples/khr-3hv/full project/controllers/supervisorsManager/Args.py
> +        self.observation_filter = observation_filter
Do you think we can use something like [`**kwargs`]() to pass these hyperparameters instead of using Args.py?
Check out this link:  [**kwargs](https://book.pythontips.com/en/latest/args_and_kwargs.html#args-and-kwargs)
If you think it is better this way (Args.py), please keep it.

2021-08-31 02:43 UTC, KelvinYang0320 commented on examples/khr-3hv/full project/controllers/supervisorsManager/supervisorsManager.py
> +               OUTPUT, args)
Do you think we can use something like [`**kwargs`]() to pass these hyperparameters instead of using Args.py?
Check out this link:  [**kwargs](https://book.pythontips.com/en/latest/args_and_kwargs.html#args-and-kwargs)
```python
    PPORun.run(PROJECT_NAME, WANDB_SAVE_FREQ, TRAIN, USE_Ray,
               OUTPUT, lr=lr, gamma=gamma, gae_lambda=gae_lambda, 
                     clip_param=clip_param, kl_coeff=kl_coeff, 
                     num_sgd_iter=num_sgd_iter, 
                     sgd_minibatch_size=sgd_minibatch_size,
                     train_batch_size=train_batch_size, 
                     num_workers=num_workers, num_gpus=num_gpus,
                     batch_mode=batch_mode, 
                     observation_filter=observation_filter)
```
If you think it is better this way (Args.py), please keep it.

2021-08-31 02:43 UTC, KelvinYang0320 commented on examples/khr-3hv/README.md
> +wandb`
https://githubmemory.com/repo/aio-libs/aioredis/issues/1082
Please note that ray==1.2.0 doesn't support new version of aioredis, which causes _AttributeError: module 'aioredis' has no attribute 'create_redis_pool' when USE_Ray = True_
I downgraded aioredis to v1.3.1 to run and keep reviewing your work for now.

2021-08-31 02:43 UTC, KelvinYang0320 commented on examples/khr-3hv/full project/controllers/supervisorsManager/PPORun.py
> +    return func
Remove these lines?

2021-08-31 02:43 UTC, KelvinYang0320 commented on examples/khr-3hv/full project/controllers/supervisorsManager/PPORun.py
> +            model = PPO.load("./results/Deepbots-khr3hv-SB-reward-weight,prev_pos,obs-x,y,z,vel-done-0.5-RNN-5,clip_range-0.2,lr-0.0001_6778500_steps")
Maybe we can pass a file path in `supervisorsManager.py`.

2021-08-31 02:43 UTC, KelvinYang0320 commented on examples/khr-3hv/full project/controllers/supervisorsManager/PPORun.py
> +            # Crate an agent having the predifined model hyperparameters
Add ray.init()?
When `TRAIN = False` and `USE_Ray = True`, I get _System error: Ray has not been started yet. You can start Ray with 'ray.init()'._

2021-08-31 02:43 UTC, KelvinYang0320 commented on examples/khr-3hv/full project/controllers/supervisorsManager/PPORun.py
> +            agent.restore("./results/Deepbots-khr3hv-Ray-reward-weight,prev_pos,obs-x,y,z,vel-done-0.5-RNN-5,clip_range-0.2,lr-0.0001_6778500_steps")
Maybe we can pass a file path in `supervisorsManager.py`.

2021-08-31 02:43 UTC, KelvinYang0320 commented on examples/khr-3hv/full project/controllers/supervisorsManager/khr3hvEnv.py
> +from gym.spaces import Box, Discrete
```suggestion
from gym.spaces import Box
```

2021-08-31 03:03 UTC, KelvinYang0320 commented
@NickKok Thank you for contributing many examples to deepworlds!
Also, the code quality is great!

This PR includes
* [khr-3hv](https://www.cyberbotics.com/doc/guide/khr-3hv?version=master)
* [nao](https://www.cyberbotics.com/doc/guide/nao)
* cartpole with stable baselines

I only do the code review on khr-3hv as the description of this PR.
Could you separate these examples into different branches and open PR for each?
And write the title & description for each PR according to changed files.
In this way, I think we can discuss or record these examples more clearly. Thanks! :smile:

2021-09-06 12:07 UTC, NickKok commented
Hello @KelvinYang0320.

No I didn't get any error on : AttributeError: module 'aioredis' has no attribute 'create_redis_pool' when USE_Ray = True?

When you downgraded aioredis to v1.3.1, does it work with Ray?

2021-09-06 14:40 UTC, NickKok commented on examples/khr-3hv/full project/controllers/supervisorsManager/PPORun.py
> +from ray.tune import grid_search
When using Ray. It is needed the tune, register_env. Regarding the ray and grid_serach, I could remove those.

2021-09-06 14:41 UTC, NickKok commented on examples/khr-3hv/full project/controllers/supervisorsManager/PPORun.py
> +from ray.tune.integration.wandb import wandb_mixin
I need the ppo and the WandbLoggerCallback to log the results on wandb.

2021-09-06 14:47 UTC, NickKok commented on examples/khr-3hv/full project/controllers/supervisorsManager/PPORun.py
> +    return func
I believe this is something that we could use in the future. It's for the learning rate scheduler when using Stable-Baseline PPO.

2021-09-06 14:47 UTC, NickKok commented on examples/khr-3hv/full project/controllers/supervisorsManager/PPORun.py
> +            model = PPO.load("./results/Deepbots-khr3hv-SB-reward-weight,prev_pos,obs-x,y,z,vel-done-0.5-RNN-5,clip_range-0.2,lr-0.0001_6778500_steps")
Yes it could be possible

2021-09-06 15:03 UTC, KelvinYang0320 commented
> When you downgraded aioredis to v1.3.1, does it work with Ray?

@NickKok Yes, everything goes fine when downgrading aioredis to v1.3.1, as suggested on this [website](https://githubmemory.com/repo/aio-libs/aioredis/issues/1082).
I follow your [readme](https://github.com/eellak-gsoc2021/deepbots-stable/tree/dev/examples/khr-3hv#prerequisites) to pip install all packages.
Could you start from pip install these packages again to see if you can reproduce this problem?
Thank you

2021-09-09 14:22 UTC, KelvinYang0320 commented on examples/khr-3hv/full project/controllers/supervisorsManager/PPORun.py
> +from ray.tune import grid_search
@NickKok Hi, sorry for the confusion.
I mean that we can remove `grid_search` & `ray` and keep `tune`. Thanks!

2021-09-09 14:23 UTC, KelvinYang0320 commented on examples/khr-3hv/full project/controllers/supervisorsManager/PPORun.py
> +from ray.tune.integration.wandb import wandb_mixin
Sorry for the confusion.
I think we can remove `wandb_mixin` only. Thanks!

2021-09-09 14:27 UTC, KelvinYang0320 commented on examples/khr-3hv/full project/controllers/supervisorsManager/PPORun.py
> +    return func
Okay. I think we can keep these lines then.

2021-09-09 14:32 UTC, KelvinYang0320 commented on examples/khr-3hv/full project/controllers/supervisorsManager/PPORun.py
> +            model = PPO.load("./results/Deepbots-khr3hv-SB-reward-weight,prev_pos,obs-x,y,z,vel-done-0.5-RNN-5,clip_range-0.2,lr-0.0001_6778500_steps")
Please address this on a following PR. Thank you!

2022-06-29 12:56 UTC, tsampazk commented
Hey @NickKok! We would like to take over this PR and finalize it if you don't mind, unless you have some free time to do so yourself. You could resolve whatever comments exist right now, merge it and we can take over perfecting it later.

This needs to be closed in combination with other fixes we've been doing for #58, so as to bring all existing examples up to speed with the latest Webots release.

2022-06-29 14:56 UTC, NickKok commented
Hello @tsampazk. It won't be possible to work on it till the end of August. After that It might be possibl during weekends. If you would like to continue the work feel free. I could help you from September.

2022-06-29 20:48 UTC, tsampazk commented
Alright @NickKok, thanks for the quick response, we will probably continue working on this and finalize it soon then. There's always more work to be done so if you feel like it you can contribute in the future 😃

2022-11-16 09:39 UTC, tsampazk commented
Hey @KelvinYang0320, could we close this PR as i think all the goals were met by #76 ?

2022-11-16 14:15 UTC, KelvinYang0320 commented
@tsampazk There are three examples, cartpole, khr-3hv, and nao, in this PR.
* https://github.com/aidudezzz/deepworlds/pull/49#issuecomment-908858497

I think we can close this PR and open an issue for it. What do you think?

2022-11-16 14:19 UTC, tsampazk commented
Oh yes i didn't notice the other two, sorry. The cartpole stable-baselines stuff are already present in the dev branch :confused:, so we need a new PR that adds the nao example? Bottom line i think it's better to close it and open an issue as you suggested!

2022-11-16 14:19 UTC, closed without merging

2022-11-16 14:31 UTC, KelvinYang0320 commented
@tsampazk I have a `nao` branch on my fork. Do you want me to open a draft PR or push it to a new branch on aidudezzz/deepworlds directly?
As for cartpole, I think he also modified our existing cartpole stable-baselines. Unfortunately, I cannot remember the detail. :confused:

2022-11-16 14:45 UTC, tsampazk commented
> @tsampazk I have a `nao` branch on my fork. Do you want me to open a draft PR or push it to a new branch on aidudezzz/deepworlds directly? 
I don't mind, whatever you feel is easier for you!

> As for cartpole, I think he also modified our existing cartpole stable-baselines. Unfortunately, I cannot remember the detail. confused

It's ok, by taking a quick look at the sb cartpole we need to refactor and update that example anyway!