Pit Escape fixes and new reset procedure
aidudezzz/deepworlds pull request #56
Opened 2022-06-02 12:23 UTC by tsampazk

- Updated and fixed the world file for the new coordinate system
- Updated the supervisor to use the new reset procedure, along with several fixes in bugs introduced from the new reset method, e.g. how time is handled per episode

2022-06-08 11:02 UTC, tsampazk commented
Converted this to draft. Discovered that the world uses a non-default coordinate system that needs to be fixed.

2022-06-22 07:55 UTC, ManosMagnus approved these changes, later dismissed

2022-06-22 08:04 UTC, KelvinYang0320 requested changes
Thank you for fixing pit_escape. 😃
Sorry for the late review. 
I have left some comments.

2022-06-22 08:04 UTC, KelvinYang0320 commented on examples/pit_escape/pit_escape_discrete/controllers/supervisor_manager/utilities.py
> +    return (distanceX * distanceX + distanceY * distanceY)**0.5  # square root
One minor suggestion:
Maybe we can use `sqrt()`. It is slightly faster than `**0.5` and more intuitive.
https://gist.github.com/zed/783011#file-claudiu-py-L33-L44
https://stackoverflow.com/questions/327002/which-is-faster-in-python-x-5-or-math-sqrtx

2022-06-22 08:04 UTC, KelvinYang0320 commented on examples/pit_escape/pit_escape_discrete/worlds/pit_escape.wbt
> +  translation 0 0.06 0
Initial translation should be (0, 0, 0) since we use  `position - 0` in our [`getDistanceFromCenter()`](https://github.com/aidudezzz/deepworlds/blob/b765d2257abab4b713472dc9c045643751bf0610/examples/pit_escape/pit_escape_discrete/controllers/supervisor_manager/utilities.py#L16-L17).
```suggestion
  translation 0 0 0
```

2022-06-22 08:07 UTC, tsampazk commented on examples/pit_escape/pit_escape_discrete/controllers/supervisor_manager/utilities.py
> +    return (distanceX * distanceX + distanceY * distanceY)**0.5  # square root
Hey @KelvinYang0320 , thanks for the review! Do you mean `math.sqrt()`? I think i originally didn't use it to avoid an extra import, but it's not a big deal, i will change it.

2022-06-22 08:10 UTC, KelvinYang0320 commented on examples/pit_escape/pit_escape_discrete/controllers/supervisor_manager/utilities.py
> +    return (distanceX * distanceX + distanceY * distanceY)**0.5  # square root
Yes, I think `math.sqrt` is better since we will compute this square root for many times during training.

2022-06-22 08:30 UTC, KelvinYang0320 approved these changes

2022-06-22 08:31 UTC, merged