Find and avoid v2
aidudezzz/deepworlds pull request #88
Opened 2023-03-03 10:16 UTC by tsampazk

2023-03-21 08:03 UTC, tsampazk commented
Updating the description and also uploading a trained agent within the day.

2023-03-21 10:41 UTC, tsampazk commented
I did some git juggling to remove the merge commit from dev i did earlier and did a rebase instead. I think all went well as far as i can tell. There is some dirty history in the (310) commits that's from older versions i worked on, but i guess what's done is done now, it will get squashed eventually.

2023-03-27 13:05 UTC, tsampazk commented
Some more git/github shenanigans happened, nothing much changed since i requested reviews, just renaming of a variable and an update of the main env docstring that had a TODO before

2023-03-30 14:53 UTC, KelvinYang0320 requested changes
@tsampazk  I have left a few comments for the README.
Some of my suggestions may not be very good.
I will review the code another time.

2023-03-30 14:53 UTC, KelvinYang0320 commented on examples/find_and_avoid_v2/README.md
> +and distance sensor values and its latest action. The observation can also be augmented with observations
Would you think the following suggestion is better?
``` suggestion
The agent observes its distance to the target, relative facing angle, motor speeds, touch
and distance sensor values, and latest action. The observation can also be augmented with observations 
```

2023-03-30 14:53 UTC, KelvinYang0320 commented on examples/find_and_avoid_v2/README.md
> +the speeds of the left and right motor, while avoiding obstacles using the distance and touch sensors.
``` suggestion
the left and right motor speeds while avoiding obstacles using the distance and touch sensors.
```

2023-03-30 14:53 UTC, KelvinYang0320 commented on examples/find_and_avoid_v2/README.md
> +chairs and jars. With the help of a grid-map, there are two ways the map can be randomized. The first one
Would you think the following suggestion is better?
``` suggestion
chairs, and jars. With the help of a grid map, the map can be randomized in two ways. The first one
```

2023-03-30 14:53 UTC, KelvinYang0320 commented on examples/find_and_avoid_v2/README.md
> +places the robot and the target at random positions, with variable distance between them to control difficulty,
``` suggestion
places the robot and the target at random positions, with a variable distance between them to control difficulty,
```

2023-03-30 14:53 UTC, KelvinYang0320 commented on examples/find_and_avoid_v2/README.md
> +The second way of randomizing the map, creates a corridor with several rows and three columns. The robot is
``` suggestion
The second way of randomizing the map creates a corridor with several rows and three columns. The robot is
```

2023-03-30 14:53 UTC, KelvinYang0320 commented on examples/find_and_avoid_v2/README.md
> +placed on the first row and the target is placed on one of the other rows which can be controlled to modify difficulty.
``` suggestion
placed on the first row, and the target is placed on one of the other rows, which can be controlled to modify difficulty.
```

2023-03-30 14:53 UTC, KelvinYang0320 commented on examples/find_and_avoid_v2/README.md
> +The training happens in a curriculum of increasing difficulty. First a random map is used with a few scattered
``` suggestion
The training happens in a curriculum of increasing difficulty. First, a random map is used with a few scattered 
```

2023-03-30 14:53 UTC, KelvinYang0320 commented on examples/find_and_avoid_v2/README.md
> +that are mostly free of obstacles, providing an easy start.  Next, using the corridor randomization, training continues
Would you think the following suggestion is better?
``` suggestion
obstacles and the target placed at a large distance. This way, paths between the robot and the target 
are mostly free of obstacles, providing an easy start. Next, using the corridor randomization, training continues
```

2023-03-30 14:53 UTC, KelvinYang0320 commented on examples/find_and_avoid_v2/README.md
> +with more and more obstacles added for each row.
``` suggestion
starting with one row of obstacles and increasing gradually between training sessions to two, three, and so on, 
with more and more obstacles added for each row. 
```

2023-03-30 14:53 UTC, KelvinYang0320 commented on examples/find_and_avoid_v2/README.md
> +between the robot and the target.
``` suggestion
Finally, the agent is trained on a random map, with all 25 available obstacles placed within and a varying distance 
between the robot and the target.
```

2023-03-30 14:53 UTC, KelvinYang0320 commented on examples/find_and_avoid_v2/README.md
> +difficulties and a random map setup, for 100 episodes each.
``` suggestion
difficulties and a random map setup for 100 episodes each.
```

2023-03-30 14:53 UTC, KelvinYang0320 commented on examples/find_and_avoid_v2/README.md
> +Tensorboard is used to log various aspects of the training procedure. For watching the tensorboard logs, navigate to
I think "to watch" is better.
``` suggestion
Tensorboard is used for logging various aspects of the training procedure. To watch the tensorboard logs, navigate to 
```

2023-03-30 14:53 UTC, KelvinYang0320 commented on examples/find_and_avoid_v2/README.md
> +and STD reward are recorded.
I don't quite understand "sb3 evaluation mean and STD reward".
Do you mean the mean and STD of the reward from the sb3 evaluation?
``` suggestion
For testing, a CSV file is produced that includes the reward per episode, how the episode ended (collision, timeout, 
or reached target), as well as the steps taken until the end of the episode. Moreover, the sb3 evaluated mean 
and STD reward are recorded.
```

2023-03-30 16:46 UTC, tsampazk commented
Thank you @KelvinYang0320! No worries, i will apply the fixes to the readme and feel free to review the rest when you can :smile:

2023-04-03 07:21 UTC, tsampazk commented on examples/find_and_avoid_v2/README.md
> +and STD reward are recorded.
Yes, the `evaluate` method returns the average reward achieved by the agent as well as the standard deviation of the reward between episodes. I will try to rephrase it in another way to make it more clear.

2023-04-03 07:37 UTC, tsampazk commented on examples/find_and_avoid_v2/README.md
> +and STD reward are recorded.
https://github.com/aidudezzz/deepworlds/pull/88/commits/3df70b97d52856499d1ff1c2f5c87efceae4b8f0

Let me know how this looks! :)

2023-07-07 08:37 UTC, tsampazk commented
I'll go ahead and merge this as i need to include the regular link to the code for the relevant paper and we can revisit it later if needed. In general i feel that the example is in a great spot and only some details might need more work. As soon as the paper is published i will add it in the relevant README.

2023-07-07 08:37 UTC, merged